defaults:
  - _self_
  - logger: tensorboard

datamodule:
  _target_: src.datamodules.mnist_datamodule.MNISTDataModule
  save_dir: ../data
  batch_size: 64
  num_workers: 4

model:
  _target_: src.models.mnist_mlp.MLP
  input_dim: 784
  hidden_dim: 128
  output_dim: 10
  lr: 0.001
  lr_decay: 0.95

checkpoint:
  _target_: src.utils.callbacks.RemoteModelCheckpoint
  monitor: val_loss
  mode: min
  save_top_k: 1
  dirpath: ../checkpoints
  filename: "{epoch}-{val_loss:.2f}"

trainer:
  precision: 32
  max_epochs: 5
  accelerator: auto
  devices: 1

seed: 42